build:
  image: docker:git
  services:
    - gbraad/dind-options:latest
  variables:
    DOCKER_HOST: "tcp://gbraad__dind-options:2375"
  before_script:
    - docker login -u gbraad -p $DOCKER_PASSWORD
    - docker login -u gbraad -p $GITLAB_TOKEN registry.gitlab.com
  script:
    - docker build -t godot-server:2.1.4 . 
    - docker tag godot-server:2.1.4 gbraad/godot-server:2.1.4
    - docker push gbraad/godot-server:2.1.4
    - docker tag godot-server:2.1.4 registry.gitlab.com/gbraad/godot-server:2.1.4
    - docker push registry.gitlab.com/gbraad/godot-server:2.1.4
  only:
    - master

